Document: hybridstore
Title: Debian hybridstore Manual
Author: <insert document author here>
Abstract: This manual describes what hybridstore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hybridstore/hybridstore.sgml.gz

Format: postscript
Files: /usr/share/doc/hybridstore/hybridstore.ps.gz

Format: text
Files: /usr/share/doc/hybridstore/hybridstore.text.gz

Format: HTML
Index: /usr/share/doc/hybridstore/html/index.html
Files: /usr/share/doc/hybridstore/html/*.html
